apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: prow-jobs-scraper-xg3v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: prow-jobs-scraper-xg3v
    app.kubernetes.io/part-of: prow-jobs-scraper
  name: prow-jobs-scraper-xg3v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: prow-jobs-scraper-xg3v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prow-jobs-scraper-xg3v
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
